# Ksyxis is a third-party mod for Minecraft Java Edition that
# speed ups your world loading by removing spawn chunks.
#
# MIT License
#
# Copyright (c) 2021-2026 VidTu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/VidTu/Ksyxis/issues"

[[mods]]
modId = "ksyxis"
version = "${version}"
displayName = "Ksyxis"
updateJSONURL = "https://raw.githubusercontent.com/VidTu/Ksyxis/main/updater_ksyxis_neoforge.json"
displayURL = "https://modrinth.com/mod/ksyxis"
issueTrackerURL = "https://github.com/VidTu/Ksyxis/issues"
catalogueImageIcon = "ksyxis_64.png"
catalogueItemIcon = "minecraft:porkchop"
catalogueBackground = "ksyxis_background.png"
itemIcon = "minecraft:porkchop"
logoFile = "ksyxis_240.png"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''Speed up your world loading by removing spawn chunks.'''

[[mixins]]
config = "ksyxis.mixins.json"

[[dependencies.ksyxis]]
modId = "minecraft"
type = "required"
reason = "Ksyxis doesn't support versions newer than 1.21.8. Spawn chunks were removed in the 25w31a snapshot, therefore the mod is now useless."
mandatory = true
versionRange = "[,1.21.8]"
ordering = "NONE"
side = "BOTH"

[modproperties.ksyxis]
catalogueImageIcon = "ksyxis_64.png"
catalogueItemIcon = "minecraft:porkchop"
catalogueBackground = "ksyxis_background.png"
itemIcon = "minecraft:porkchop"
logoFile = "ksyxis_240.png"
